/* Carrier catalogue: every carrier the shop can offer, with how it can be connected.
   Pure data, safe to import in the browser. The server registry in ./index.ts turns each entry into a
   working adapter by the best available route: a direct API, Balíkobot, Zásilkovna's external
   carriers, or manual entry with a tracking link. */
export type CarrierGroup = "cz" | "sk" | "eu" | "freight" | "own";
export type CarrierService = "pickup" | "box" | "address" | "pallet" | "express" | "sameday";
export interface CarrierDef {
  id: string;
  label: string;
  group: CarrierGroup;
  services: CarrierService[];
  tracking: (n: string) => string;
  /** Environment variables a direct API adapter needs (all must be set). */
  env?: string[];
  /** Balíkobot shipper code and default service code; override the service with BALIKOBOT_SERVICE_<SHIPPER>. */
  balikobot?: { shipper: string; service: string };
  /** Packeta "external carrier" id, bookable through the Zásilkovna contract. Verify in Packeta's carrier list. */
  packetaCarrierId?: number;
  docs?: string;
  note: { cs: string; en: string };
}
const enc = encodeURIComponent;

export const CARRIERS: CarrierDef[] = [
  { id: "dealer", label: "Vlastní doprava / osobní odběr", group: "own", services: ["address", "pickup"], tracking: () => "", note: { cs: "Vozidla: předání na prodejně nebo dovoz vlastním přívěsem.", en: "Vehicles: handover at the shop or delivery with the dealer's trailer." } },
  // ── Czech parcel networks ──
  { id: "packeta", label: "Zásilkovna / Packeta", group: "cz", services: ["pickup", "box", "address"], tracking: (n) => `https://tracking.packeta.com/cs/?id=${enc(n)}`, env: ["PACKETA_API_PASSWORD"], balikobot: { shipper: "zasilkovna", service: "1" }, docs: "https://docs.packeta.com", note: { cs: "Z-Point, Z-BOX, doručení na adresu. Přes stejnou smlouvu jdou i externí dopravci (Balík Do ruky, PPL…).", en: "Z-Point, Z-BOX, home delivery. The same contract also books external carriers (Balík Do ruky, PPL…)." } },
  { id: "ceska_posta", label: "Česká pošta – Balík Do ruky / Na poštu", group: "cz", services: ["address", "pickup"], tracking: (n) => `https://www.postaonline.cz/trackandtrace/-/zasilka/cislo?parcelNumbers=${enc(n)}`, env: ["CESKA_POSTA_API_TOKEN", "CESKA_POSTA_SECRET_KEY", "CESKA_POSTA_CUSTOMER_ID", "CESKA_POSTA_LOCATION_NUMBER"], balikobot: { shipper: "cp", service: "DR" }, packetaCarrierId: 13, docs: "https://www.ceskaposta.cz/en/napi/b2b", note: { cs: "Do 30 kg, nejdelší strana 200 cm. B2B smlouva přes obchodního zástupce.", en: "Up to 30 kg, longest side 200 cm. B2B contract via a sales representative." } },
  { id: "balikovna", label: "Balíkovna (Česká pošta)", group: "cz", services: ["pickup", "box"], tracking: (n) => `https://www.postaonline.cz/trackandtrace/-/zasilka/cislo?parcelNumbers=${enc(n)}`, env: ["CESKA_POSTA_API_TOKEN", "CESKA_POSTA_SECRET_KEY", "CESKA_POSTA_CUSTOMER_ID", "CESKA_POSTA_LOCATION_NUMBER"], balikobot: { shipper: "cp", service: "NB" }, docs: "https://www.balikovna.cz/cs/firmy", note: { cs: "Výdejní místa na poštách a v boxech, max. 50 × 50 × 50 cm. Stejné B2B napojení jako Balík Do ruky.", en: "Pickup at post offices and boxes, max 50 × 50 × 50 cm. Same B2B connection as Balík Do ruky." } },
  { id: "ppl", label: "PPL (DHL Group)", group: "cz", services: ["address", "pickup", "box"], tracking: (n) => `https://www.ppl.cz/vyhledat-zasilku?shipmentId=${enc(n)}`, env: ["PPL_CLIENT_ID", "PPL_CLIENT_SECRET"], balikobot: { shipper: "ppl", service: "2" }, packetaCarrierId: 25, docs: "https://ppl-cpl-api.apidog.io", note: { cs: "Parcel CZ Private, ParcelShop, ParcelBox a AlzaBox. Do 31,5 kg.", en: "Parcel CZ Private, ParcelShop, ParcelBox and AlzaBox. Up to 31.5 kg." } },
  { id: "dpd", label: "DPD", group: "cz", services: ["address", "pickup", "box"], tracking: (n) => `https://tracking.dpd.de/status/cs_CZ/parcel/${enc(n)}`, env: ["DPD_API_KEY", "DPD_CUSTOMER_ID"], balikobot: { shipper: "dpd", service: "1" }, docs: "https://www.dpd.cz/api/Shipping_API/DPD_Shipping_API.pdf", note: { cs: "Private, Pickup, DPD Box. Do 31,5 kg. API klíč vydává podpora DPD.", en: "Private, Pickup, DPD Box. Up to 31.5 kg. API key issued by DPD support." } },
  { id: "gls", label: "GLS", group: "cz", services: ["address", "pickup", "box"], tracking: (n) => `https://gls-group.eu/CZ/cs/sledovani-zasilek?match=${enc(n)}`, env: ["GLS_USERNAME", "GLS_PASSWORD", "GLS_CLIENT_NUMBER"], balikobot: { shipper: "gls", service: "1" }, docs: "https://api.mygls.cz/docs/", note: { cs: "ParcelShop, GLS Box, AlzaBox, doručení na adresu do 40 kg.", en: "ParcelShop, GLS Box, AlzaBox, home delivery up to 40 kg." } },
  { id: "wedo", label: "One by Allegro (WE|DO)", group: "cz", services: ["pickup", "box", "address"], tracking: (n) => `https://onedelivery.cz/sledovani/${enc(n)}`, env: ["WEDO_API_TOKEN"], balikobot: { shipper: "wedo", service: "1" }, docs: "https://api.wedo.cz/v2/", note: { cs: "ONE POINT, ONE BOX, ONE COURIER. Smluvní ceny.", en: "ONE POINT, ONE BOX, ONE COURIER. Contract prices." } },
  { id: "alzabox", label: "AlzaBox", group: "cz", services: ["box"], tracking: (n) => `https://www.alza.cz/sledovani-zasilky?id=${enc(n)}`, balikobot: { shipper: "ppl", service: "3" }, note: { cs: "Samoobslužné boxy Alzy. Doručuje se přes PPL nebo GLS, přímé napojení jen pro velké e-shopy.", en: "Alza self-service boxes. Delivered via PPL or GLS; direct integration only for large shops." } },
  { id: "dodo", label: "DoDo (kurýr)", group: "cz", services: ["sameday", "address"], tracking: (n) => `https://dodo.cz/sledovani/${enc(n)}`, balikobot: { shipper: "dodo", service: "1" }, note: { cs: "Doručení týž den ve velkých městech.", en: "Same-day delivery in larger cities." } },
  { id: "liftago", label: "Liftago", group: "cz", services: ["sameday", "address"], tracking: (n) => `https://www.liftago.com/sledovani/${enc(n)}`, balikobot: { shipper: "liftago", service: "1" }, note: { cs: "Doručení týž den, Praha a Brno.", en: "Same-day delivery, Prague and Brno." } },
  { id: "messenger", label: "Messenger", group: "cz", services: ["sameday", "address"], tracking: (n) => `https://www.messenger.cz/sledovani-zasilky/${enc(n)}`, balikobot: { shipper: "messenger", service: "1" }, note: { cs: "Kurýr po Praze a středních Čechách.", en: "Courier in Prague and Central Bohemia." } },
  // ── pallets and heavy goods ──
  { id: "toptrans", label: "Toptrans", group: "freight", services: ["pallet", "address"], tracking: (n) => `https://www.toptrans.cz/preprava/cs/sledovani-zasilky/?cislo=${enc(n)}`, balikobot: { shipper: "toptrans", service: "1" }, note: { cs: "Balíky do 31,5 kg i palety do 1 500 kg, doručení další pracovní den. Sady pneu, radlice, čtyřkolky.", en: "Parcels to 31.5 kg and pallets to 1 500 kg, next working day. Tyre sets, ploughs, ATVs." } },
  { id: "fofr", label: "FOFR", group: "freight", services: ["pallet", "address"], tracking: (n) => `https://www.fofr.cz/sledovani-zasilky/?cislo=${enc(n)}`, balikobot: { shipper: "fofr", service: "1" }, note: { cs: "Paletová přeprava po ČR a SR.", en: "Pallet freight across CZ and SK." } },
  { id: "geis", label: "Geis", group: "freight", services: ["pallet", "address"], tracking: (n) => `https://www.geis-group.cz/cs/sledovani-zasilky?number=${enc(n)}`, balikobot: { shipper: "geis", service: "1" }, note: { cs: "Paletová a kusová přeprava, ČR i zahraničí.", en: "Pallet and groupage freight, domestic and international." } },
  { id: "raben", label: "Raben", group: "freight", services: ["pallet"], tracking: (n) => `https://myraben.com/tracking?number=${enc(n)}`, balikobot: { shipper: "raben", service: "1" }, note: { cs: "Paletová přeprava, silná v Polsku a Německu.", en: "Pallet freight, strong in Poland and Germany." } },
  { id: "dachser", label: "Dachser", group: "freight", services: ["pallet"], tracking: (n) => `https://elogistics.dachser.com/shipmentstatus/?q=${enc(n)}`, balikobot: { shipper: "dachser", service: "1" }, note: { cs: "Mezinárodní paletová přeprava.", en: "International pallet freight." } },
  { id: "gebruder_weiss", label: "Gebrüder Weiss", group: "freight", services: ["pallet"], tracking: (n) => `https://www.gw-world.com/cs/sledovani-zasilek/?number=${enc(n)}`, balikobot: { shipper: "gw", service: "1" }, note: { cs: "Paletová přeprava, Rakousko a střední Evropa.", en: "Pallet freight, Austria and central Europe." } },
  { id: "dbschenker", label: "DB Schenker", group: "freight", services: ["pallet"], tracking: (n) => `https://www.dbschenker.com/app/tracking-public/?refNumber=${enc(n)}`, balikobot: { shipper: "dbschenker", service: "1" }, note: { cs: "Mezinárodní kusová a paletová přeprava.", en: "International groupage and pallet freight." } },
  // ── Slovakia ──
  { id: "packeta_sk", label: "Packeta Slovensko", group: "sk", services: ["pickup", "box", "address"], tracking: (n) => `https://tracking.packeta.com/sk/?id=${enc(n)}`, env: ["PACKETA_API_PASSWORD"], balikobot: { shipper: "zasilkovna", service: "1" }, note: { cs: "Stejná smlouva jako Zásilkovna, výdejní místa na Slovensku.", en: "Same contract as Zásilkovna, Slovak pickup points." } },
  { id: "slovenska_posta", label: "Slovenská pošta", group: "sk", services: ["address", "pickup"], tracking: (n) => `https://tandt.posta.sk/zasielky/${enc(n)}`, balikobot: { shipper: "sp", service: "1" }, note: { cs: "Balík na adresu a na poštu v SR.", en: "Parcels to an address or post office in Slovakia." } },
  { id: "sps", label: "SPS – Slovak Parcel Service", group: "sk", services: ["address", "pickup"], tracking: (n) => `https://www.sps-sro.sk/sledovanie-zasielok?number=${enc(n)}`, balikobot: { shipper: "sps", service: "1" }, note: { cs: "Kurýr po Slovensku.", en: "Courier across Slovakia." } },
  { id: "kurier123", label: "123Kuriér", group: "sk", services: ["address", "pickup"], tracking: (n) => `https://www.123kurier.sk/sledovanie-zasielky?id=${enc(n)}`, balikobot: { shipper: "kurier", service: "1" }, note: { cs: "Kurýr po Slovensku.", en: "Courier across Slovakia." } },
  // ── Europe and world ──
  { id: "dhl_express", label: "DHL Express", group: "eu", services: ["express", "address"], tracking: (n) => `https://www.dhl.com/cz-cs/home/tracking.html?tracking-id=${enc(n)}`, balikobot: { shipper: "dhl", service: "1" }, note: { cs: "Expresní zásilky do zahraničí.", en: "Express shipments abroad." } },
  { id: "ups", label: "UPS", group: "eu", services: ["express", "address"], tracking: (n) => `https://www.ups.com/track?loc=cs_CZ&tracknum=${enc(n)}`, balikobot: { shipper: "ups", service: "1" }, note: { cs: "Balíky do zahraničí.", en: "International parcels." } },
  { id: "fedex", label: "FedEx / TNT", group: "eu", services: ["express", "address"], tracking: (n) => `https://www.fedex.com/fedextrack/?trknbr=${enc(n)}`, balikobot: { shipper: "fedex", service: "1" }, note: { cs: "Expresní a ekonomické zásilky do zahraničí.", en: "Express and economy shipments abroad." } },
  { id: "inpost", label: "InPost (Polsko)", group: "eu", services: ["box", "address"], tracking: (n) => `https://inpost.pl/sledzenie-przesylek?number=${enc(n)}`, balikobot: { shipper: "inpost", service: "1" }, note: { cs: "Paczkomaty v Polsku.", en: "Parcel lockers in Poland." } },
  { id: "hungarian_post", label: "Magyar Posta", group: "eu", services: ["address", "pickup"], tracking: (n) => `https://www.posta.hu/nyomkovetes/nyitooldal?searchvalue=${enc(n)}`, balikobot: { shipper: "magyarposta", service: "1" }, note: { cs: "Balíky do Maďarska.", en: "Parcels to Hungary." } },
  { id: "posta_bez_hranic", label: "Pošta bez hranic", group: "eu", services: ["address", "pickup"], tracking: (n) => `https://www.postabezhranic.cz/sledovani-zasilky?number=${enc(n)}`, balikobot: { shipper: "pbh", service: "1" }, note: { cs: "Levné doručení do celé EU přes místní pošty.", en: "Low-cost delivery across the EU through local posts." } },
];
export const carrierDef = (id: string) => CARRIERS.find((c) => c.id === id);
export const trackingUrlFor = (id: string, n: string) => carrierDef(id)?.tracking(n) ?? "";
export const GROUP_LABEL: Record<CarrierGroup, { cs: string; en: string }> = { own: { cs: "Vlastní", en: "Own" }, cz: { cs: "Česko – balíky", en: "Czechia – parcels" }, freight: { cs: "Palety a těžké zboží", en: "Pallets and heavy goods" }, sk: { cs: "Slovensko", en: "Slovakia" }, eu: { cs: "Evropa a svět", en: "Europe and world" } };
export const SERVICE_LABEL: Record<CarrierService, { cs: string; en: string }> = { pickup: { cs: "výdejní místo", en: "pickup point" }, box: { cs: "box", en: "locker" }, address: { cs: "na adresu", en: "to address" }, pallet: { cs: "paleta", en: "pallet" }, express: { cs: "expres", en: "express" }, sameday: { cs: "týž den", en: "same day" } };
