#!/usr/bin/env node
/* Generate supabase/seed.sql from src/data/catalog.ts and the default settings. */
import { readFileSync, writeFileSync } from "node:fs";
import ts from "typescript";

const src = readFileSync("src/data/catalog.ts", "utf8");
const js = ts.transpileModule(src, { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2020 } }).outputText;
const mod = { exports: {} };
new Function("module", "exports", "require", js)(mod, mod.exports, () => ({}));
const { products, categories } = mod.exports;

const q = (v) => v === undefined || v === null ? "null" : `'${String(v).replace(/'/g, "''")}'`;
const j = (v) => `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`;
const arr = (a) => `array[${(a ?? []).map(q).join(",")}]::text[]`;

let sql = `-- generated by scripts/seed.mjs · ${new Date().toISOString()}\n`;
sql += `insert into public.categories (slug, label, blurb, sort) values\n` + categories.map((c, i) =>
  `(${q(c.slug)}, ${j(c.label)}, ${j(c.blurb)}, ${i})`).join(",\n") +
  `\non conflict (slug) do update set label = excluded.label, blurb = excluded.blurb, sort = excluded.sort;\n\n`;

sql += `insert into public.products (slug, brand, category, name, price, old_price, homologation, cc, power, drive, short, specs, colors, tags, status, stock, featured, sort) values\n` +
  products.map((p, i) => `(${q(p.slug)}, ${q(p.brand)}, ${q(p.category)}, ${q(p.name)}, ${p.price}, ${p.oldPrice ?? "null"}, ${q(p.homologation)}, ${p.cc ?? "null"}, ${q(p.power)}, ${q(p.drive)}, ${j(p.short)}, ${j(p.specs)}, ${j(p.colors)}, ${arr(p.tags)}, 'active', ${p.category === "prislusenstvi" ? 25 : 2}, ${["kentoya-v-cross-125-4t","cfmoto-gladiator-x520-g2","cfmoto-450-mt-r","tgb-blade-600-ltx-max-eps-e5","linhai-landforce-650l-eps","cfmoto-gladiator-u6-ev","tumoto-nexy-plus-125","cfmoto-gladiator-x1000"].includes(p.slug)}, ${i})`).join(",\n") +
  `\non conflict (slug) do update set brand = excluded.brand, category = excluded.category, name = excluded.name, price = excluded.price, old_price = excluded.old_price, homologation = excluded.homologation, cc = excluded.cc, power = excluded.power, drive = excluded.drive, short = excluded.short, specs = excluded.specs, colors = excluded.colors, tags = excluded.tags, sort = excluded.sort;\n\n`;

const shipping = [
  { id: "pickup", carrier: "dealer", name: { cs: "Osobní odběr, Golčův Jeníkov", en: "Pick up in Golčův Jeníkov" }, description: { cs: "Zdarma, předání a zaškolení na prodejně.", en: "Free, handover and briefing at the showroom." }, price: 0, vehicles: true, sort: 0 },
  { id: "dealer_delivery", carrier: "dealer", name: { cs: "Doprava vozidla na adresu", en: "Vehicle delivery to your address" }, description: { cs: "Vlastním přívěsem po celé ČR.", en: "On our own trailer across Czechia." }, price: 2500, vehicles: true, sort: 1 },
  { id: "packeta_point", carrier: "packeta", name: { cs: "Zásilkovna – výdejní místo", en: "Packeta pickup point" }, description: { cs: "Příslušenství do 10 kg.", en: "Accessories up to 10 kg." }, price: 89, free_over: 3000, needs_pickup_point: true, sort: 2 },
  { id: "packeta_home", carrier: "packeta", name: { cs: "Zásilkovna – na adresu", en: "Packeta home delivery" }, description: {}, price: 129, free_over: 3000, sort: 3 },
  { id: "ppl", carrier: "ppl", name: { cs: "PPL – na adresu", en: "PPL to address" }, description: {}, price: 139, free_over: 5000, sort: 4 },
  { id: "dpd", carrier: "dpd", name: { cs: "DPD – na adresu", en: "DPD to address" }, description: {}, price: 139, free_over: 5000, sort: 5 },
  { id: "ceska_posta", carrier: "ceska_posta", name: { cs: "Česká pošta – Balík do ruky", en: "Czech Post parcel" }, description: {}, price: 119, free_over: 5000, sort: 6 },
  { id: "gls", carrier: "gls", name: { cs: "GLS – na adresu", en: "GLS to address" }, description: {}, price: 129, free_over: 5000, sort: 7 },
  { id: "fofr", carrier: "fofr", name: { cs: "FOFR – paletová přeprava", en: "FOFR pallet freight" }, description: { cs: "Těžké díly a pneumatiky na paletě.", en: "Heavy parts and tyres on a pallet." }, price: 690, sort: 8 },
];
sql += `insert into public.shipping_methods (id, carrier, name, description, price, free_over, enabled, needs_pickup_point, vehicles, sort) values\n` +
  shipping.map((s) => `(${q(s.id)}, ${q(s.carrier)}, ${j(s.name)}, ${j(s.description)}, ${s.price}, ${s.free_over ?? "null"}, true, ${!!s.needs_pickup_point}, ${!!s.vehicles}, ${s.sort})`).join(",\n") +
  `\non conflict (id) do nothing;\n\n`;

const payments = [
  ["stripe", { cs: "Platební karta (Stripe)", en: "Card (Stripe)" }, true, 0],
  ["gopay", { cs: "GoPay", en: "GoPay" }, false, 1],
  ["comgate", { cs: "Comgate", en: "Comgate" }, false, 2],
  ["paypal", { cs: "PayPal", en: "PayPal" }, false, 3],
  ["bank_transfer", { cs: "Bankovní převod", en: "Bank transfer" }, true, 4],
  ["cash", { cs: "Hotově při odběru", en: "Cash on collection" }, true, 5],
];
sql += `insert into public.payment_methods (id, name, enabled, test_mode, config, sort) values\n` +
  payments.map(([id, name, en, sort]) => `(${q(id)}, ${j(name)}, ${en}, true, '{}'::jsonb, ${sort})`).join(",\n") + `\non conflict (id) do nothing;\n\n`;

const settings = {
  store: { name: "Moto Dvořák", legal: "Dvořák a synové s.r.o.", address: "Nádraží 604, 582 82 Golčův Jeníkov", phone: "+420 603 235 182", email: "servis@elektrodvorak.cz", ico: "", dic: "", hours: { cs: "Pondělí až pátek 7:30 – 16:00", en: "Monday to Friday 7:30 – 16:00" }, currency: "CZK", locales: ["cs", "en"], defaultLocale: "cs" },
  theme: { accent: "#111111", signal: "#d0021b", font: "Inter", radius: 0, buttonStyle: "uppercase" },
  announcement: { enabled: true, text: { cs: "Prodejna a servis Golčův Jeníkov · Po–Pá 7:30–16:00 · +420 603 235 182", en: "Showroom and service, Golčův Jeníkov · Mon–Fri 7:30–16:00 · +420 603 235 182" } },
  taxes: { vatRate: 21, pricesIncludeVat: true },
  notifications: { orderEmailTo: "servis@elektrodvorak.cz", customerConfirmation: true },
  checkout: { allowGuest: true, termsUrl: "/obchodni-podminky/", requirePhone: true },
};
sql += `insert into public.settings (key, value) values\n` + Object.entries(settings).map(([k, v]) => `(${q(k)}, ${j(v)})`).join(",\n") + `\non conflict (key) do nothing;\n\n`;

const home = [
  { id: "hero", type: "hero", media: { kind: "image", url: "" }, eyebrow: { cs: "Novinka 2026 · Kentoya", en: "New for 2026 · Kentoya" }, title: { cs: "V-Cross 125", en: "V-Cross 125" }, text: { cs: "14 koní, ABS a ASR, osmipalcový displej. Nejlépe vybavená stodvacetpětka, jakou Kentoya kdy postavila.", en: "14 hp, ABS and ASR, an eight-inch display. The best-equipped 125 Kentoya has ever built." }, cta: { label: { cs: "Prohlédnout", en: "View model" }, href: "/produkt/kentoya-v-cross-125-4t/" }, productSlug: "kentoya-v-cross-125-4t", align: "left", height: "large", overlay: 60 },
  { id: "cats", type: "categories", eyebrow: { cs: "Sortiment", en: "Range" }, title: { cs: "Čtyři řady, jedna dílna.", en: "Four lines, one workshop." }, text: { cs: "Všechno, co prodáme, také servisujeme.", en: "Everything we sell, we also service." }, categories: ["ctyrkolky", "utv", "motocykly", "skutry"] },
  { id: "featured", type: "products", eyebrow: { cs: "Vybrané modely", en: "Featured models" }, title: { cs: "Právě skladem", en: "In stock now" }, source: "featured", limit: 8 },
  { id: "campaign", type: "banner", media: { kind: "image", url: "" }, eyebrow: { cs: "Pracovní čtyřkolky", en: "Utility ATVs" }, title: { cs: "Postavené pro les, pole a zimu.", en: "Built for forest, field and winter." }, text: { cs: "CFMOTO, Linhai a TGB s traktorovou homologací T3b.", en: "CFMOTO, Linhai and TGB with T3b tractor homologation." }, cta: { label: { cs: "Zobrazit čtyřkolky", en: "See ATVs" }, href: "/ctyrkolky/" } },
  { id: "video", type: "video", title: { cs: "Podívejte se do dílny", en: "Look inside the workshop" }, video: { kind: "youtube", url: "" }, text: { cs: "Krátká prohlídka servisu a showroomu v Golčově Jeníkově.", en: "A short tour of the workshop and showroom in Golčův Jeníkov." } },
  { id: "brands", type: "brands", eyebrow: { cs: "Značky", en: "Brands" }, title: { cs: "Autorizovaný prodej a servis", en: "Authorised sales and service" } },
  { id: "service", type: "split", media: { kind: "image", url: "" }, eyebrow: { cs: "Servis", en: "Service" }, title: { cs: "Servis, který zná váš stroj.", en: "Service that knows your machine." }, text: { cs: "Záruční i pozáruční servis čtyřkolek, skútrů a zahradní techniky.", en: "Warranty and post-warranty service for ATVs, scooters and garden machinery." }, cta: { label: { cs: "Objednat servis", en: "Book a service" }, href: "/servis/" } },
];
sql += `insert into public.pages (slug, title, sections, status) values ('home', ${j({ cs: "Domů", en: "Home" })}, ${j(home)}, 'published')\non conflict (slug) do nothing;\n`;

writeFileSync("supabase/seed.sql", sql);
console.log(`wrote supabase/seed.sql (${products.length} products, ${categories.length} categories)`);
