-- Moto Dvořák shop · initial schema
-- Run in the Supabase SQL editor or with `supabase db push`.

create extension if not exists pgcrypto;

-- ───────────────────────── staff / roles ─────────────────────────
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  full_name text,
  role text not null default 'staff' check (role in ('owner','admin','staff')),
  created_at timestamptz not null default now()
);

create or replace function public.handle_new_user() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, email, full_name, role)
  values (
    new.id, new.email, coalesce(new.raw_user_meta_data->>'full_name', ''),
    case when (select count(*) from public.profiles) = 0 then 'owner' else 'staff' end
  );
  return new;
end $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
  for each row execute function public.handle_new_user();

create or replace function public.is_staff() returns boolean
language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.profiles where id = auth.uid());
$$;

-- ───────────────────────── catalog ─────────────────────────
create table if not exists public.categories (
  slug text primary key,
  label jsonb not null,            -- {"cs":"","en":""}
  blurb jsonb not null default '{}',
  image_url text,
  video_url text,
  sort int not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists public.products (
  id uuid primary key default gen_random_uuid(),
  slug text unique not null,
  brand text not null,
  category text not null references public.categories(slug),
  name text not null,
  price numeric(12,2) not null default 0,
  old_price numeric(12,2),
  homologation text not null default '—',
  cc int,
  power text,
  drive text,
  short jsonb not null default '{}',
  description jsonb not null default '{}',
  specs jsonb not null default '[]',
  colors jsonb not null default '[]',
  tags text[] not null default '{}',
  status text not null default 'active' check (status in ('draft','active','archived')),
  stock int not null default 0,
  sku text,
  images jsonb not null default '[]',   -- [{url, alt}]
  videos jsonb not null default '[]',   -- [{kind:'upload'|'youtube'|'vimeo', url, title}]
  seo jsonb not null default '{}',
  featured boolean not null default false,
  sort int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists products_category_idx on public.products(category, status);

-- ───────────────────────── commerce ─────────────────────────
create table if not exists public.customers (
  id uuid primary key default gen_random_uuid(),
  email text unique not null,
  name text,
  phone text,
  address jsonb,
  notes text,
  marketing boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  number bigint generated by default as identity,
  customer_email text not null,
  customer_name text,
  phone text,
  shipping_address jsonb,
  items jsonb not null default '[]',     -- [{slug,name,price,qty,image}]
  subtotal numeric(12,2) not null default 0,
  shipping_cost numeric(12,2) not null default 0,
  discount_code text,
  discount_amount numeric(12,2) not null default 0,
  total numeric(12,2) not null default 0,
  currency text not null default 'CZK',
  status text not null default 'pending' check (status in ('pending','paid','processing','fulfilled','cancelled','refunded')),
  payment_provider text,
  payment_status text not null default 'unpaid' check (payment_status in ('unpaid','pending','paid','failed','refunded')),
  payment_ref text,
  shipping_method text,
  shipping_carrier text,
  pickup_point jsonb,
  tracking_number text,
  label_url text,
  notes text,
  timeline jsonb not null default '[]',
  locale text not null default 'cs',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists orders_created_idx on public.orders(created_at desc);

create table if not exists public.discounts (
  id uuid primary key default gen_random_uuid(),
  code text unique not null,
  type text not null check (type in ('percent','fixed','free_shipping')),
  value numeric(12,2) not null default 0,
  min_total numeric(12,2),
  starts_at timestamptz,
  ends_at timestamptz,
  usage_limit int,
  used int not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.shipping_methods (
  id text primary key,
  carrier text not null,               -- packeta|ppl|dpd|ceska_posta|fofr|gls|pickup|dealer
  name jsonb not null,
  description jsonb not null default '{}',
  price numeric(12,2) not null default 0,
  free_over numeric(12,2),
  enabled boolean not null default true,
  needs_pickup_point boolean not null default false,
  vehicles boolean not null default false,  -- can carry whole vehicles
  sort int not null default 0
);

create table if not exists public.payment_methods (
  id text primary key,                  -- stripe|gopay|comgate|paypal|bank_transfer|cash
  name jsonb not null,
  enabled boolean not null default false,
  test_mode boolean not null default true,
  config jsonb not null default '{}',   -- public, non-secret config only
  sort int not null default 0
);

-- ───────────────────────── content ─────────────────────────
create table if not exists public.pages (
  slug text primary key,
  title jsonb not null default '{}',
  sections jsonb not null default '[]',
  status text not null default 'draft' check (status in ('draft','published')),
  seo jsonb not null default '{}',
  updated_at timestamptz not null default now()
);

create table if not exists public.settings (
  key text primary key,
  value jsonb not null default '{}',
  updated_at timestamptz not null default now()
);

create table if not exists public.media (
  id uuid primary key default gen_random_uuid(),
  path text not null,
  url text not null,
  kind text not null check (kind in ('image','video','file')),
  mime text,
  size bigint,
  alt jsonb not null default '{}',
  created_at timestamptz not null default now()
);

-- updated_at maintenance
create or replace function public.touch_updated_at() returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end $$;
do $$ declare t text;
begin
  foreach t in array array['products','orders','pages','settings','categories'] loop
    execute format('drop trigger if exists touch_%s on public.%s', t, t);
    execute format('create trigger touch_%s before update on public.%s for each row execute function public.touch_updated_at()', t, t);
  end loop;
end $$;

-- ───────────────────────── row level security ─────────────────────────
alter table public.profiles enable row level security;
alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.customers enable row level security;
alter table public.orders enable row level security;
alter table public.discounts enable row level security;
alter table public.shipping_methods enable row level security;
alter table public.payment_methods enable row level security;
alter table public.pages enable row level security;
alter table public.settings enable row level security;
alter table public.media enable row level security;

create policy "profiles self or staff" on public.profiles for select using (id = auth.uid() or public.is_staff());
create policy "profiles owner manages" on public.profiles for all using (exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'owner'));

create policy "public read categories" on public.categories for select using (true);
create policy "staff write categories" on public.categories for all using (public.is_staff()) with check (public.is_staff());

create policy "public read active products" on public.products for select using (status = 'active' or public.is_staff());
create policy "staff write products" on public.products for all using (public.is_staff()) with check (public.is_staff());

create policy "staff customers" on public.customers for all using (public.is_staff()) with check (public.is_staff());
create policy "staff orders" on public.orders for all using (public.is_staff()) with check (public.is_staff());
create policy "staff discounts" on public.discounts for all using (public.is_staff()) with check (public.is_staff());

create policy "public read shipping" on public.shipping_methods for select using (enabled or public.is_staff());
create policy "staff write shipping" on public.shipping_methods for all using (public.is_staff()) with check (public.is_staff());
create policy "public read payments" on public.payment_methods for select using (enabled or public.is_staff());
create policy "staff write payments" on public.payment_methods for all using (public.is_staff()) with check (public.is_staff());

create policy "public read published pages" on public.pages for select using (status = 'published' or public.is_staff());
create policy "staff write pages" on public.pages for all using (public.is_staff()) with check (public.is_staff());
create policy "public read settings" on public.settings for select using (true);
create policy "staff write settings" on public.settings for all using (public.is_staff()) with check (public.is_staff());
create policy "public read media" on public.media for select using (true);
create policy "staff write media" on public.media for all using (public.is_staff()) with check (public.is_staff());

-- ───────────────────────── storage ─────────────────────────
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('media', 'media', true, 524288000, array['image/*','video/*'])
on conflict (id) do update set public = true, file_size_limit = 524288000;

create policy "public read media files" on storage.objects for select using (bucket_id = 'media');
create policy "staff upload media" on storage.objects for insert with check (bucket_id = 'media' and public.is_staff());
create policy "staff update media" on storage.objects for update using (bucket_id = 'media' and public.is_staff());
create policy "staff delete media" on storage.objects for delete using (bucket_id = 'media' and public.is_staff());

-- ───────────────────────── dashboard helpers ─────────────────────────
create or replace function public.sales_by_day(days int default 30)
returns table(day date, orders bigint, revenue numeric)
language sql stable security definer set search_path = public as $$
  select d::date as day,
         count(o.id) as orders,
         coalesce(sum(o.total) filter (where o.payment_status = 'paid'), 0) as revenue
  from generate_series(current_date - (days - 1), current_date, interval '1 day') d
  left join public.orders o on o.created_at::date = d::date and o.status <> 'cancelled'
  group by d order by d;
$$;
